# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 448c417b6edd457020fe57da8707d4fe06ac65098bc44591293902aef5d0ebbe08b38760c6b5a17bb96edcfdd040a38e82ef75aebe1f63db4717e7f1920504f1

test:
  secret_key_base: 0352e93635dc5f40f44294df846e4f6ffc2a50c1b2c0971847d290eb9fc56a30836cd3611de3cb52b6ff7e6986116512deed8cad692d578b82e4a3c17f962fc4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
